# Settings for main header
header:
  title: My Octopress Blog
  subtitle:
 
# Links for main navigation
nav:
  - { url: '/', title: 'Home' }
  - { url: '/archive/', title: 'Archive' }
  - { url: '/feed/', title: 'RSS' }

# Settings for category generator
category:
  title:  Category
  dir:   'categories'
  feeds: false
    
  # The base url for categories
  # An empty string means categories will live at the root directory.

  # To add per category feeds, use an array of category names you want feeds for.
  # for example:
  # feeds:
  #   - news
  #   - programming

post_index:
  excerpt_articles: true
  permalink_label: "Permalink"
  read_more_label: "Continue Reading &rarr;"

feeds:
  count: 10
  main_feed: true
  linkpost_feed: true
  article_feed: true
  excerpt_articles: false

center_headings: true
search: google
