# Settings for main header
title: My Octopress Blog
subtitle:
 
# Links for main navigation
nav:
  - { url: '/', title: 'Posts' }
  - { url: '/archive/', title: 'Archive' }
  - { url: '/feed/', title: 'Subscribe' }

post_index:
  excerpt_articles: false
  permalink_label: "Permalink"
  read_more_label: "Continue Reading &rarr;"

search: google

center_headings: false
