# Settings for main header
title: My Octopress Blog
subtitle:
 
# Links for main navigation
nav:
  - { url: '/', title: 'Posts' }
  - { url: '/archive/', title: 'Archive' }
  - { url: '/feed/', title: 'Subscribe' }

# Link labels
permalink_label: "Permalink"
read_more_label: "Continue Reading →"

# Show excerpts on post index?
excerpt_index: false

search: google

sharing:
  - facebook
  - twitter
  - gplus
  - email

share_with: links
comments: false
excerpt_posts: true
excerpt_linkposts: false


center_headings: true

