# Settings for main header
header:
  title: My Octopress Blog
 
# Links for main navigation
nav:
  - { url: '/', title: 'Posts' }
  - { url: '/archive', title: 'Archive' }
  - { url: '/feed', title: 'RSS' }

# Settings for category index generator
category:
  prefix: Category
  url:    category

post_index:
  excerpt_posts: true

center-headings: true
